### ISSUE TITLE
DataBase diagram

### ISSUE THREAD

**Issue by Likemilk99** [Likemilk99/librarian2#6]
Develop a class diagram of the our project.

**Comment by laiola** [comment]
We are going to use noSQL or we will use relational db?

**Comment by Likemilk99** [comment]
I think we must use relational DB, becouse our projecte have a lot of relationships between tables.
Why do you offer the NoSQL DB ?

**Comment by laiola** [comment]
User (id, login, email, password)
Book(id, name)
Description(id, id_author, year, series, description)
Author(id, first_name, last_name)

**Comment by laiola** [comment]
![db](https://cloud.githubusercontent.com/assets/17079863/21468172/4690308e-ca17-11e6-8d02-69d8e6a793f7.png)
